:- module(core, [
    api_version/1,
    linha_sils/3,
    verso_ln/2,
    gera_de_texto/4
]).
:- encoding(utf8).
% ============================================================
%  core.pl — Language-agnostic orchestration layer
%
%  Camada de orquestração agnóstica de língua.
%
%  Calls into g2p, phonetics, and html_report via qualified
%  calls — it expects those modules to have been loaded by
%  the caller (e.g. a language-specific pipeline or a temp
%  loader generated by the CLI).
%
%  Chama g2p, phonetics e html_report via chamadas qualificadas
%  — espera que esses módulos já tenham sido carregados por
%  quem o chamou (pipeline da língua ou loader temporário).
% ============================================================

%! api_version(-Version) is det.
%  API version atom for the CLI to verify compatibility.
api_version('1.0.0').

%! linha_sils(+Text, -Syllables, -IPA) is det.
%  Converts a verse text into concatenated sil/5 structures and IPA.
%  Converte um verso de texto em sílabas sil/5 concatenadas e IPA.
linha_sils(Texto, Sils, IPA) :-
    split_string(Texto, " ", "", P0),
    exclude(==(""), P0, Pedacos),
    maplist(palavra_sils, Pedacos, Listas, IPAs),
    append(Listas, Sils),
    atomic_list_concat(IPAs, ' ', IPA).

palavra_sils(Str, Sils, IPA) :-
    atom_string(A, Str),
    catch(g2p:g2p(A, Sils, IPA),
          _,
          ( Sils = [], IPA = '?' )).

%! verso_ln(+Text, -LnRecord) is det.
%  Converts verse text into ln(Text, IPA, Counts, rima(ConsTail, AssoTail)).
%  Dispatches to phonetics:tradicao_padrao/1 for the tradition atom.
%
%  Converte texto em ln(Texto, IPA, Contagens, rima(CaudaConsoante, CaudaToante)).
%  Usa phonetics:tradicao_padrao/1 para obter o átomo de tradição.
verso_ln(Texto, ln(Texto, IPA, Cont, rima(Cons, Toa))) :-
    linha_sils(Texto, Sils, IPA),
    phonetics:tradicao_padrao(Trad),
    phonetics:contagens(Trad, Sils, Cont),
    ( phonetics:cauda_consoante(Sils, Cons) -> true ; Cons = '?' ),
    ( phonetics:cauda_toante(Sils, Toa)     -> true ; Toa  = '?' ).

%! gera_de_texto(+File, +Title, +Form, +StanzasText) is det.
%  End-to-end: list of stanzas of text strings -> HTML file.
%  De ponta a ponta: lista de estrofes de strings -> arquivo HTML.
gera_de_texto(Arquivo, Titulo, Forma, EstrofesTxt) :-
    maplist(maplist(verso_ln), EstrofesTxt, EstrofesLn),
    html_report:gera_html(Arquivo, Titulo, Forma, "pt-BR", EstrofesLn).
